# Generated by Django 3.2.8 on 2021-10-19 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puppyuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('rating', models.IntegerField(default=1)),
                ('userType', models.CharField(choices=[('Owner', 'Owner'), ('Renter', 'Renter')], default='Owner', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='puppy',
            name='user',
        ),
        migrations.DeleteModel(
            name='PupOwner',
        ),
        migrations.AddField(
            model_name='pupuser',
            name='puppy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='puppyuser.puppy'),
        ),
        migrations.AddField(
            model_name='pupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookedapps',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puppyuser.pupuser'),
        ),
    ]
