# Generated by Django 3.2.8 on 2021-10-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppyuser', '0002_auto_20211019_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='age',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='vaccinated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
