# Generated by Django 3.2.8 on 2021-10-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppyuser', '0003_auto_20211019_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pupuser',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pupuser',
            name='street_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pupuser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
