# Generated by Django 3.2.8 on 2021-10-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppyuser', '0004_auto_20211019_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
