# Generated by Django 3.2.8 on 2021-10-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppyuser', '0005_auto_20211024_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
