# Generated by Django 3.2.8 on 2021-10-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppyuser', '0007_auto_20211024_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupuser',
            name='latitude',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pupuser',
            name='longitude',
            field=models.FloatField(default=0, null=True),
        ),
    ]
