# Generated by Django 3.2.8 on 2021-10-24 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puppyuser', '0008_auto_20211024_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='YYYY-MM-DD')),
                ('timeslot', models.IntegerField(choices=[[0, '0:00 - 1'], [1, '1:00 - 2'], [2, '2:00 - 3'], [3, '3:00 - 4'], [4, '4:00 - 5'], [5, '5:00 - 6'], [6, '6:00 - 7'], [7, '7:00 - 8'], [8, '8:00 - 9'], [9, '9:00 - 10'], [10, '10:00 - 11'], [11, '11:00 - 12'], [12, '12:00 - 13'], [13, '13:00 - 14'], [14, '14:00 - 15'], [15, '15:00 - 16'], [16, '16:00 - 17'], [17, '17:00 - 18'], [18, '18:00 - 19'], [19, '19:00 - 20'], [20, '20:00 - 21'], [21, '21:00 - 22'], [22, '22:00 - 23'], [23, '23:00 - 24']])),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=5)),
                ('text', models.TextField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pupuser',
            name='rating',
        ),
        migrations.AddField(
            model_name='pupuser',
            name='available_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pupuser',
            name='available_until',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='BookedApps',
        ),
        migrations.AddField(
            model_name='rating',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puppyuser.pupuser'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='enthusiast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enthusiast', to='puppyuser.pupuser'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='puppyuser.pupuser'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('owner', 'date', 'timeslot')},
        ),
    ]
