# Generated by Django 3.2.8 on 2021-10-24 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puppyuser', '0009_auto_20211025_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rating',
            name='fromUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to='puppyuser.pupuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to='puppyuser.pupuser'),
        ),
    ]
