# Generated by Django 3.2.8 on 2021-10-24 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puppyuser', '0010_auto_20211025_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='puppy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_puppy', to='puppyuser.puppy'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('puppy', 'date', 'timeslot')},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='owner',
        ),
    ]
