# Generated by Django 3.2.8 on 2021-10-25 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puppyuser', '0012_alter_appointment_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='toUser',
        ),
        migrations.AddField(
            model_name='rating',
            name='toPuppy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='toPuppy', to='puppyuser.puppy'),
            preserve_default=False,
        ),
    ]
