# Generated by Django 3.2.8 on 2021-10-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppyuser', '0013_auto_20211025_0339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('toPuppy', 'fromUser')},
        ),
    ]
